version: '3.8'
services:
  db:
    image: postgres:9.6
    container_name: pg-algafood-db
    environment:
      - POSTGRES_DB=algafood-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - .docker/dev_data:/var/lib/postgresql