version: '3.8'
services:
  api:
    build:
      context: ./algafood-api
      dockerfile: ./Dockerfile
    image: algafood/api
    ports:
      - '8080:8080'
      - '5005:5005'
#    networks: 
#      - algafood-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/algafood-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    links: 
      - db
  db:
    image: postgres:9.6
    container_name: pg-algafood-db
    environment:
      - POSTGRES_DB=algafood-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
#    networks: 
#      - algafood-network
    volumes:
      - .docker/dev_data:/var/lib/postgresql
#networks:
#  algafood-network: 
#    driver: bridge 
# volumes:
#   dev_data: