version: '3'
services:
  db:
    image: postgres:9.6
    container_name: pg-algafood-db
    environment:
      - POSTGRES_DB=algafood-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - .docker/dev_data:/var/lib/postgresql

  sonarqube:
    container_name: sonar
    image: sonarqube:7.9.2-community
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://pg-sonar:5432/sonar
    depends_on:
      - pg-sonar
    volumes:
      - .docker/sonarqube_conf:/opt/sonarqube/conf
      - .docker/sonarqube_data:/opt/sonarqube/data
      - .docker/sonarqube_extensions:/opt/sonarqube/extensions
      - .docker/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  pg-sonar:
    container_name: pg-sonar
    image: postgres:9.6
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    
networks:
  sonarnet:
volumes:
  postgresql:
  postgresql_data: