# docker-compose -f stack.yml up
# mvn sonar:sonar -Dsonar.projectKey=br.com.portfolio:algafood-api -Dsonar.host.url=http://localhost:9000 -Dsonar.login=a47d5a9da8555630554594d6479387cc8cb5d9ac
# http://localhost:8080/api/algafood/swagger-ui/index.html?configUrl=/api/algafood/v3/api-docs/swagger-config
server:
  port: 8080
  servlet:
    context-path: /api/algafood
spring:
  profiles:
    active: local
#  servlet:
#    multipart:
#      max-file-size: 20KB
#      max-request-size: 20MB
  jackson:
#    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
#  data:
#    jpa:
#      repositories:
#        enabled: true
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: 
springdoc:
  swagger-ui:
    path: /swagger-ui.html
